### ISSUE TITLE
Panel de admin

### ISSUE THREAD

**Issue by Nidev-lab** [Luis-aramayo-18/Rolling-Restaurant#13]
## Proceso

1. Me loguee con un usuario admin.
2. Navegue por la pagina.
3. Quise cargar un producto nuevo.

## Resultado esperado

Encontrar un boton que redireccione a la seccion panel de administracion.

## Resultado actual

No hay un boton disponible que me lleve a dicha seccion.

## Posible solucion

Agregar un boton que redireccione al panel de admin para registrar o administrar los producto.

## Captura

![image](https://user-images.githubusercontent.com/53904695/229864136-617d7e42-c70e-475d-a697-c12d5cbc9075.png)

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by Luis-aramayo-18** [comment]
Ya se añadio los botones de navegacion para el Admin
