### ISSUE TITLE
Problemas de responsividad 

### ISSUE THREAD

**Issue by Nidev-lab** [Luis-aramayo-18/Rolling-Restaurant#14]
## Proceso

1. Me loguee con un usuario admin.
       (Panel de adminitrador)
3. Hice responsive en mobile y en patalla menor a 1065px.

## Resultado esperado

Que al hacer responsive no se corrompa.

## Resultado actual

Al hacer responsive se rompe.

## Captura

![image](https://user-images.githubusercontent.com/53904695/229865705-fe6ae435-f213-4023-98d7-a141746cb8f1.png)

![image](https://user-images.githubusercontent.com/53904695/229868661-76dc5530-0673-4e1a-8fe0-eed09622faf4.png)

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by paubejarano** [comment]
Gracias por tu devolución Nico, ya esta corregido el responsive de esta sección.
